/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as energyAuctionSol from './EnergyAuction.sol/index.js';
export type { energyAuctionSol };
import type * as marketplaceSol from './Marketplace.sol/index.js';
export type { marketplaceSol };
export type { EnergyCertificate } from './EnergyCertificate.js';
export type { EnergyToken } from './EnergyToken.js';
export * as factories from './factories/index.js';
export type { EnergyAuction } from './EnergyAuction.sol/EnergyAuction.js';
export { EnergyAuction__factory } from './factories/EnergyAuction.sol/EnergyAuction__factory.js';
export type { IEnergyCertificate } from './EnergyAuction.sol/IEnergyCertificate.js';
export { IEnergyCertificate__factory } from './factories/EnergyAuction.sol/IEnergyCertificate__factory.js';
export { EnergyCertificate__factory } from './factories/EnergyCertificate__factory.js';
export { EnergyToken__factory } from './factories/EnergyToken__factory.js';
export type { Marketplace } from './Marketplace.sol/Marketplace.js';
export { Marketplace__factory } from './factories/Marketplace.sol/Marketplace__factory.js';