/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Marketplace {
      
    export type ListingStruct = {id: BigNumberish, seller: AddressLike, amount: BigNumberish, pricePerUnit: BigNumberish, isActive: boolean}

    export type ListingStructOutput = [id: bigint, seller: string, amount: bigint, pricePerUnit: bigint, isActive: boolean] & {id: bigint, seller: string, amount: bigint, pricePerUnit: bigint, isActive: boolean }
  
    }

  export interface MarketplaceInterface extends Interface {
    getFunction(nameOrSignature: "buyEnergy" | "cancelListing" | "energyToken" | "getActiveListings" | "listEnergy" | "listingCount" | "listings" | "owner"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EnergyListed" | "EnergyPurchased" | "ListingCancelled"): EventFragment;

    encodeFunctionData(functionFragment: 'buyEnergy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelListing', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'energyToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'getActiveListings', values?: undefined): string;
encodeFunctionData(functionFragment: 'listEnergy', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'listingCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'listings', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'buyEnergy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'energyToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getActiveListings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listEnergy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listingCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  }

  
    export namespace EnergyListedEvent {
      export type InputTuple = [listingId: BigNumberish, seller: AddressLike, amount: BigNumberish, pricePerUnit: BigNumberish];
      export type OutputTuple = [listingId: bigint, seller: string, amount: bigint, pricePerUnit: bigint];
      export interface OutputObject {listingId: bigint, seller: string, amount: bigint, pricePerUnit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EnergyPurchasedEvent {
      export type InputTuple = [listingId: BigNumberish, buyer: AddressLike, seller: AddressLike, amount: BigNumberish, totalPrice: BigNumberish];
      export type OutputTuple = [listingId: bigint, buyer: string, seller: string, amount: bigint, totalPrice: bigint];
      export interface OutputObject {listingId: bigint, buyer: string, seller: string, amount: bigint, totalPrice: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ListingCancelledEvent {
      export type InputTuple = [listingId: BigNumberish, seller: AddressLike];
      export type OutputTuple = [listingId: bigint, seller: string];
      export interface OutputObject {listingId: bigint, seller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Marketplace extends BaseContract {
    
    connect(runner?: ContractRunner | null): Marketplace;
    waitForDeployment(): Promise<this>;

    interface: MarketplaceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    buyEnergy: TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    cancelListing: TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    energyToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getActiveListings: TypedContractMethod<
      [],
      [Marketplace.ListingStructOutput[]],
      'view'
    >
    

    
    listEnergy: TypedContractMethod<
      [amount: BigNumberish, pricePerUnit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    listingCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    listings: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, boolean] & {id: bigint, seller: string, amount: bigint, pricePerUnit: bigint, isActive: boolean }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'buyEnergy'): TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'cancelListing'): TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'energyToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getActiveListings'): TypedContractMethod<
      [],
      [Marketplace.ListingStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'listEnergy'): TypedContractMethod<
      [amount: BigNumberish, pricePerUnit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'listingCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'listings'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, boolean] & {id: bigint, seller: string, amount: bigint, pricePerUnit: bigint, isActive: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'EnergyListed'): TypedContractEvent<EnergyListedEvent.InputTuple, EnergyListedEvent.OutputTuple, EnergyListedEvent.OutputObject>;
getEvent(key: 'EnergyPurchased'): TypedContractEvent<EnergyPurchasedEvent.InputTuple, EnergyPurchasedEvent.OutputTuple, EnergyPurchasedEvent.OutputObject>;
getEvent(key: 'ListingCancelled'): TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;

    filters: {
      
      'EnergyListed(uint256,address,uint256,uint256)': TypedContractEvent<EnergyListedEvent.InputTuple, EnergyListedEvent.OutputTuple, EnergyListedEvent.OutputObject>;
      EnergyListed: TypedContractEvent<EnergyListedEvent.InputTuple, EnergyListedEvent.OutputTuple, EnergyListedEvent.OutputObject>;
    

      'EnergyPurchased(uint256,address,address,uint256,uint256)': TypedContractEvent<EnergyPurchasedEvent.InputTuple, EnergyPurchasedEvent.OutputTuple, EnergyPurchasedEvent.OutputObject>;
      EnergyPurchased: TypedContractEvent<EnergyPurchasedEvent.InputTuple, EnergyPurchasedEvent.OutputTuple, EnergyPurchasedEvent.OutputObject>;
    

      'ListingCancelled(uint256,address)': TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
      ListingCancelled: TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
    
    };
  }