/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IEnergyCertificate } from './IEnergyCertificate.js';
export type { Marketplace } from './Marketplace.js';