/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace EnergyAuction {
      
    export type AuctionStruct = {id: BigNumberish, seller: AddressLike, tokenAmount: BigNumberish, startingPrice: BigNumberish, endTime: BigNumberish, highestBidder: AddressLike, highestBid: BigNumberish, ended: boolean, cancelled: boolean}

    export type AuctionStructOutput = [id: bigint, seller: string, tokenAmount: bigint, startingPrice: bigint, endTime: bigint, highestBidder: string, highestBid: bigint, ended: boolean, cancelled: boolean] & {id: bigint, seller: string, tokenAmount: bigint, startingPrice: bigint, endTime: bigint, highestBidder: string, highestBid: bigint, ended: boolean, cancelled: boolean }
  
    }

  export interface EnergyAuctionInterface extends Interface {
    getFunction(nameOrSignature: "auctionCount" | "auctions" | "cancelAuction" | "createAuction" | "endAuction" | "energyCertificate" | "energyToken" | "getActiveAuctions" | "getAuction" | "owner" | "placeBid" | "setCertificateContract"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuctionCancelled" | "AuctionCreated" | "AuctionEnded" | "BidPlaced"): EventFragment;

    encodeFunctionData(functionFragment: 'auctionCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'auctions', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelAuction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createAuction', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'endAuction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'energyCertificate', values?: undefined): string;
encodeFunctionData(functionFragment: 'energyToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'getActiveAuctions', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAuction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'placeBid', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setCertificateContract', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'auctionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'auctions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'energyCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'energyToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getActiveAuctions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCertificateContract', data: BytesLike): Result;
  }

  
    export namespace AuctionCancelledEvent {
      export type InputTuple = [auctionId: BigNumberish, seller: AddressLike];
      export type OutputTuple = [auctionId: bigint, seller: string];
      export interface OutputObject {auctionId: bigint, seller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AuctionCreatedEvent {
      export type InputTuple = [auctionId: BigNumberish, seller: AddressLike, amount: BigNumberish, startingPrice: BigNumberish, endTime: BigNumberish];
      export type OutputTuple = [auctionId: bigint, seller: string, amount: bigint, startingPrice: bigint, endTime: bigint];
      export interface OutputObject {auctionId: bigint, seller: string, amount: bigint, startingPrice: bigint, endTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AuctionEndedEvent {
      export type InputTuple = [auctionId: BigNumberish, winner: AddressLike, tokenAmount: BigNumberish, finalPrice: BigNumberish];
      export type OutputTuple = [auctionId: bigint, winner: string, tokenAmount: bigint, finalPrice: bigint];
      export interface OutputObject {auctionId: bigint, winner: string, tokenAmount: bigint, finalPrice: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BidPlacedEvent {
      export type InputTuple = [auctionId: BigNumberish, bidder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [auctionId: bigint, bidder: string, amount: bigint];
      export interface OutputObject {auctionId: bigint, bidder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EnergyAuction extends BaseContract {
    
    connect(runner?: ContractRunner | null): EnergyAuction;
    waitForDeployment(): Promise<this>;

    interface: EnergyAuctionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    auctionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    auctions: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, bigint, string, bigint, boolean, boolean] & {id: bigint, seller: string, tokenAmount: bigint, startingPrice: bigint, endTime: bigint, highestBidder: string, highestBid: bigint, ended: boolean, cancelled: boolean }],
      'view'
    >
    

    
    cancelAuction: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createAuction: TypedContractMethod<
      [amount: BigNumberish, startingPrice: BigNumberish, durationMinutes: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    endAuction: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    energyCertificate: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    energyToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getActiveAuctions: TypedContractMethod<
      [],
      [EnergyAuction.AuctionStructOutput[]],
      'view'
    >
    

    
    getAuction: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [EnergyAuction.AuctionStructOutput],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    placeBid: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    setCertificateContract: TypedContractMethod<
      [_cert: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'auctionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'auctions'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, bigint, string, bigint, boolean, boolean] & {id: bigint, seller: string, tokenAmount: bigint, startingPrice: bigint, endTime: bigint, highestBidder: string, highestBid: bigint, ended: boolean, cancelled: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'cancelAuction'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createAuction'): TypedContractMethod<
      [amount: BigNumberish, startingPrice: BigNumberish, durationMinutes: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'endAuction'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'energyCertificate'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'energyToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getActiveAuctions'): TypedContractMethod<
      [],
      [EnergyAuction.AuctionStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAuction'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [EnergyAuction.AuctionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'placeBid'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'setCertificateContract'): TypedContractMethod<
      [_cert: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AuctionCancelled'): TypedContractEvent<AuctionCancelledEvent.InputTuple, AuctionCancelledEvent.OutputTuple, AuctionCancelledEvent.OutputObject>;
getEvent(key: 'AuctionCreated'): TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
getEvent(key: 'AuctionEnded'): TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
getEvent(key: 'BidPlaced'): TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;

    filters: {
      
      'AuctionCancelled(uint256,address)': TypedContractEvent<AuctionCancelledEvent.InputTuple, AuctionCancelledEvent.OutputTuple, AuctionCancelledEvent.OutputObject>;
      AuctionCancelled: TypedContractEvent<AuctionCancelledEvent.InputTuple, AuctionCancelledEvent.OutputTuple, AuctionCancelledEvent.OutputObject>;
    

      'AuctionCreated(uint256,address,uint256,uint256,uint256)': TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
      AuctionCreated: TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
    

      'AuctionEnded(uint256,address,uint256,uint256)': TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
      AuctionEnded: TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
    

      'BidPlaced(uint256,address,uint256)': TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
      BidPlaced: TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
    
    };
  }