/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EnergyAuction } from './EnergyAuction.js';
export type { IEnergyCertificate } from './IEnergyCertificate.js';