/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IEnergyCertificate, IEnergyCertificateInterface } from "../../EnergyAuction.sol/IEnergyCertificate.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "consumer",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "producer",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "mintCertificate",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IEnergyCertificate__factory {
    static readonly abi = _abi;
    static createInterface(): IEnergyCertificateInterface {
      return new Interface(_abi) as IEnergyCertificateInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IEnergyCertificate {
      return new Contract(address, _abi, runner) as unknown as IEnergyCertificate;
    }
  }
  