/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IEnergyCertificate__factory } from './IEnergyCertificate__factory.js';
export { Marketplace__factory } from './Marketplace__factory.js';